name: Mirroring

on: [push]

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: find
      run: |
        lines=$(find . -lname "*.o")
        lines+=$(find . -lname "*.a")
        lines+=$(find . -lname "*.so")
        lines+=$(find . -lname "*.gcno")
        lines+=$(find . -lname "*.gcda")
        lines+=$(find . -lname "*.gcovr")
        lines+=$(find . -lname "#*")
        lines+=$(find . -lname "*-")
        lines+=$(find . -lname "pain au chocolat")
        dir=$(find . -type d -name "tmp")
        if [ $lines -ne 0 ] && [ $dir -ne 0 ]; then
          echo "::error::Unwanted files detected: $lines"
          exit 1
        fi
  check_program_compilation:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v3
    - name: make
      run: make | timeout -k=2
    - name: clean
      run: make clean
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run_test
      run: make tests_run