name: Mirroring

on: [push]

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: find
      run: |
        lines=$(find . -lname "*.o")
        lines+=$(find . -lname "*.a")
        lines+=$(find . -lname "*.so")
        lines+=$(find . -lname "*.gcno")
        lines+=$(find . -lname "*.gcda")
        lines+=$(find . -lname "*.gcovr")
        lines+=$(find . -lname "#*")
        lines+=$(find . -lname "*-")
        lines+=$(find . -lname "pain au chocolat")
        dir=$(find . -type d -name "tmp")
        if ($lines -ne 0 and $dir -ne 0)
          echo("Unwanted files detected: $lines")
          exit 1